### ISSUE TITLE
Error 69: i don't understand...

### ISSUE THREAD

**Issue by MTtankkeo** [yuisanae2f/Container#2]
I don't even know what to say.

**Comment by yuisanae2f** [comment]
Then why did you even opened this?

**Comment by MTtankkeo** [comment]
Complete the document properly on the open source developer topic!

**Comment by yuisanae2f** [comment]
Specifically where of the document do you not understand?

**Comment by MTtankkeo** [comment]
all~

**Comment by yuisanae2f** [comment]
I am afraid to say but you seems to be lack of the background knowledge of English or Computer Science

**Comment by MTtankkeo** [comment]
You don't understand me!

**Comment by MTtankkeo** [comment]
![tmp5lereg4o](https://github.com/yuisanae2f/Container/assets/122026021/15d1b6a8-458b-4b09-bbca-a0891575da54)

**Comment by MTtankkeo** [comment]
My wife.
![profile2](https://github.com/yuisanae2f/Container/assets/122026021/e7c1dc8a-9c69-4544-a0ec-2eb0c9ec34ff)

**Comment by MTtankkeo** [comment]
i love Flutter

**Comment by yuisanae2f** [comment]
Pls do not open the case which is way too obscure.
I am going to close the case manually.
